# Generated by Django 5.0.2 on 2024-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='photo',
        ),
        migrations.AddField(
            model_name='blog',
            name='caption',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
